// <auto-generated />
namespace KW.Infrastructure
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removesektor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removesektor));
        
        string IMigrationMetadata.Id
        {
            get { return "201801122225469_remove sektor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
