// <auto-generated />
namespace KW.Infrastructure
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class createBudgetdb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createBudgetdb));
        
        string IMigrationMetadata.Id
        {
            get { return "201801122134523_create Budget db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
