// <auto-generated />
namespace KW.Infrastructure
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class createincomemodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createincomemodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201801142116358_create income model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
